### ISSUE TITLE
[Automation] Automate TODO -> Issue creation

### ISSUE THREAD

**Issue by Olshansk** [pokt-network/pocket#144]
# Objective
Automate the process of converting TODOs and other tags in the codebase into Github issues.

# Origin Document

In the main [Makefile](https://github.com/pokt-network/pocket/blob/main/Makefile#L300), we currently have this target:

```bash
### Inspired by @goldinguy_ in this post: https://goldin.io/blog/stop-using-todo ###
# TODO          - General Purpose catch-all.
# TECHDEBT      - Not a great implementation, but we need to fix it later.
# IMPROVE       - A nice to have, but not a priority. It's okay if we never get to this.
# DISCUSS       - Probably requires a lengthy offline discussion to understand next steps.
# INCOMPLETE    - A change which was out of scope of a specific PR but needed to be documented.
# INVESTIGATE   - TBD what was going on, but needed to continue moving and not get distracted.
# CLEANUP       - Like TECHDEBT, but not as bad.  It's okay if we never get to this.
# HACK          - Like TECHDEBT, but much worse. This needs to be prioritized
# REFACTOR      - Similar to TECHDEBT, but will require a substantial rewrite and change across the codebase
# CONSIDERATION - A comment that involves extra work but was thoughts / considered as part of some implementation
# INTHISCOMMIT  - SHOULD NEVER BE COMMITTED TO MASTER. It is a way for the review of a PR to start / reply to a discussion.
TODO_KEYWORDS = -e "TODO" -e "TECHDEBT" -e "IMPROVE" -e "DISCUSS" -e "INCOMPLETE" -e "INVESTIGATE" -e "CLEANUP" -e "HACK" -e "REFACTOR" -e "CONSIDERATION" -e "INTHISCOMMIT"

.PHONY: todo_list
## List all the TODOs in the project (excludes vendor and prototype directories)
todo_list:
	grep --exclude-dir={.git,vendor,prototype} -r ${TODO_KEYWORDS}  .
```

In order to track this more concretely and transparently, we can use https://github.com/DerJuulsn/todo-issue to automate that process.

# Goals / Deliverables
- [ ] Integrate the library by [@DerJuulsn](https://github.com/DerJuulsn) into Pocket V1
- [ ] Coordinate with the core v1 team to cleanup all TODOs (and other tasks) before this is merged
# Non-goals
- Create new tasks

---

Creator: @Olshansk 
Co-Owners: ???

**Comment by webbdays** [comment]
I would like to work on this.

**Comment by Olshansk** [comment]
@webbdays Sounds great! When running `make todo_count` from the main repo, we currently have `467` issues.

Before we dive into the work on this, could you do some preliminary research on whether the following would be possible:
- [ ] 1. Can we support multiple keywords as we have [in our Makefile](https://github.com/pokt-network/pocket/blob/main/Makefile#L370): `TODO`, `ADDTEST`, etc
- [ ] 2. Is there a way to eliminate the creation of a new ticket if it is already in parenthesis. For example, see [this](https://github.com/pokt-network/pocket/blob/main/consensus/types/actor_mapper.go#L31):
```go
for i, addr := range valAddresses {
		nodeId := NodeId(i + 1) // TODO(https://github.com/pokt-network/pocket/issues/434): Improve the use of NodeIDs
		am.valAddrToIdMap[addr] = nodeId
		am.idToValAddrMap[nodeId] = addr
	}
	return am
```
- [ ] 3. Can we implement the feature but temporarily have it be disabled?
- [ ] 4. Would we be able to have multiple `TODO(#XXX)` with the same `XXX` point to the same ticket without additional issue creation? 

Let me know if you have other ideas or need additional clarifications!

**Comment by webbdays** [comment]
With the present todo_count, todo_list commands  using grep there can be multiple false positives(i.e identifying non todos as todos).
So, it would be good for now to go with todo-issue (https://github.com/DerJuulsn/todo-issue).

Question 1. Can we support multiple keywords as we have [in our Makefile](https://github.com/pokt-network/pocket/blob/main/Makefile#L370): TODO, ADDTEST, etc ?
Answer : yes

This todo-issue was developed in the point of view of github actions.
But i went through some parts of the code and understood the logic.

In todo-issue regex was used to effectively parse the keywords.
And we can get todos(keywords info ) in the form of a json file and we can use it to perform necessary actions like creating issue, assigning person  based on keyword and other info beside the keyword.

I think logic for creating issue and assigning the code will be there in the todo-issue repo code. I will go through it and will get back here. 

 Question 3. Can we implement the feature but temporarily have it be disabled?
I have few questions:
 How do we want to implement the feature ? 1. As a cli for developers to list todos(keywords) 2. or As a github action like todo-issue is doing with slight logic changes as we needed here.
 

4. Would we be able to have multiple TODO(#XXX) with the same XXX point to the same ticket without additional issue creation?
Answer: yes. Here we can have json object for todos. So we can gather them and implement logic such a way to prevent additional issue creation. if issue already present then that todo can be added to the issue description.


note: we need to confirm from more technical sense that todo-issue regex is working fine in parsing todos without much false positives.
for me it seems good in general.

**Comment by webbdays** [comment]
Question 2. Is there a way to eliminate the creation of a new ticket if it is already in parenthesis. For example, see [this](https://github.com/pokt-network/pocket/blob/main/consensus/types/actor_mapper.go#L31)
Answer: I think for this to work, the tool that we are looking for need to know the language constructs of particular programming language in which the todo is there.

**Comment by webbdays** [comment]
i think we can use stack while looking for brackets and if bracket is found push.
if matching closing  bracket is found then pop both from stack.
if we found todo and the stack is not empty then we can say todo is inside some brackets. so we can ignore that todo.

**Comment by Olshansk** [comment]
@webbdays It seems like you have a really good grasp of the issue and the next steps to a solution. Let's do it!

**Comment by Olshansk** [comment]
A few questions / requests:

1. Once you get off the ground - please create a draft PR and ask questions along the way rather than trying to do it all at once.

2. If you can think of ways to split this work into more than one PR (so we can review/merge it in in smaller components), please do.

3. Please add documentation (an organized specification of the details you listed above) along with the tool.

4. Do you plan on using `todo-issue` or building it from scratch?

**Comment by Olshansk** [comment]
Closing this out as this piece of automation will likely create more noise than help.
