### ISSUE TITLE
[Roadmap] Create flows for M1 & M2 demos

### ISSUE THREAD

**Issue by jessicadaugherty** [pokt-network/pocket#349]
# Objective

Build visualizations that can be used to define the E2E demos for each iteration goal.

# Origin Document

The first version of the flows was created [here](https://www.figma.com/file/qCsQmFmVw28ZHbuLXyvfg7/Iteration-2-%2B-3%3B-end-to-end?node-id=0%3A1) using figjam.

<img width="808" alt="Screen Shot 2022-11-13 at 3 36 06 PM" src="https://user-images.githubusercontent.com/1892194/201550467-48ee9c6f-606a-480d-97f7-7782dfca548b.png">

# Goals / Deliverables 
- [x] Update existing flows to align with new timelines
- [x] Draft future flows for upcoming iteration planning
- [ ] Keep updated as new iterations are planned
- [x] Pick a tool (mermaid, figjam, etc..) for where these will live

---

Creator: @jessicadaugherty
Co-owner @Olshansk

**Comment by Olshansk** [comment]
Copy-pasting flows from an offline discussion below to use as a starting point.

--- 

### Flow: 4 Validator LocalNet demo (good tx)

1. Turn on LocalNet (k8s operator?)
    1. Check: A & B have funds
2. Use CLI to send tx from A -> B (enough funds)
3. Trigger a new round and wait for it to finish
    1. **Check**: funds moved from A to B
    2. **Check**:
        1. Tx pool funds
        2. Validator block proposal funds
        3. DAO funds

### Flow: 4 Validator LocalNet demo (bad tx)

1. Turn on LocalNet (k8s operator?)
    1. Check: A & B have funds
2. Use CLI to send tx from A -> B (not enough funds)
3. Trigger a new round and wait for it to finish
    1. **Check**: funds not moved from A to B
    2. **Check**:
        1. Tx pool funds
        2. Validator block proposal funds
        3. DAO funds

### Flow: 4 Validator + 2 Node Discovery LocalNet demo (happy)

1. Turn on LocalNet
    1. **Check**: view all the address books for peers
2. Deploy a new node on LocalNet
3. Wait for few seconds
    1. **Check**: address books peers have been updated
4. Trigger a new round and wait for it to finish
5. Deploy a new node on LocalNet
6. Wait for few seconds
    1. **Check**: address books peers have been updated

## Flow: 4 Validator + 1 Node Discovery/Churn LocalNet demo (happy)

1. Turn on LocalNet
    1. **Check**: view all the address books for peers
2. Deploy a new node on LocalNet
3. Wait for few seconds
    1. **Check**: address books peers have been updated
4. Trigger a new round and wait for it to finish
5. Kill previously deployed node on LocalNet
6. Wait for few seconds
    1. **Check**: address books peers have been updated

## Flow: 4 Validator + 1 Validator LocalNet demo w/o state sync (happy)

1. Turn on LocalNet
    1. **Check**: view all the validators in the world state
2. Deploy a new node (at genesis)
3. Wait for a few seconds
    1. **Check**: New validator is at height 0
    2. **Check:** node is added to address book and is at height 1
4. Use CLI to stake the new node as a validator
    1. **Check**: There are still 4 validators in the world state
5. Trigger a new round and wait for it to finish
    1. **Check**: There are now 5 validators in the world state
6. Trigger a few rounds (5 should be enough since we are round rosining)
    1. **Check**: The new validator was a proposer for at least one block

## Flow: 4 Validator + 1 Validator LocalNet demo w/o state sync (sad)

1. Turn on LocalNet
    1. **Check**: view all the validators in the world state
2. Deploy a new node (at genesis)
3. Wait for a few seconds
    1. **Check**: New validator is at height 0
    2. **Check:** node is added to address book and is at height 1
4. Use CLI to stake the new node as a validator
    1. **Check**: There are still 4 validators in the world state
5. Trigger a new round and wait for it to finish
    1. **Check**: There are now 5 validators in the world state
6. Trigger a new round
    1. **Check**: Make sure it passed
7. Turn off 2 validators
8. Trigger a new round, multiple times
    1. **Check**: Round cannot finish since we never get +2/3 quorum

**Flow: 4 Validator + 1 Validator LocalNet demo with state sync**

1. Turn on LocalNet
    1. **Check**: view all the validators in the world state
2. Trigger a new round a few times (e.g. 5) and wait for it to finish (i.e. move away from genesis state)
    1. Check: validators are at height 5
3. Deploy a new node (at genesis)
    1. **Check**: New validator is at height 0
4. Wait for a few seconds
    1. **Check:** node is added to address book and is at height 5
5. Trigger a new round and wait for it to finish
    1. **Check**: 4 validators are at height 6
    2. **Check**: node is at heigh 6
6. Use CLI to stake the new node as a validator
7. Trigger a new round and wait for it to finish
    1. **Check**: World state now contains 5 validators

**Comment by Olshansk** [comment]
Closing this issue as #350 is done as a foundation and it is otherwise an ongoing task.
