### ISSUE TITLE
[Tooling] Implement a TODO method for the logging module

### ISSUE THREAD

**Issue by Gustavobelfort** [pokt-network/pocket#478]
## Objective

Add a `TODO` method to the logging module to improve our workflow.

This method would allow us to add a log message with a `TODO` tag, indicating that a task is not yet completed. The method would allow us to identify these tasks and prioritize them quickly.

Example Usage:

```go
u.logger.TODO().Msg("Log message explaining the TODO")
```

## Origin Document

- The following comment from the PR that introduced logging in the codebase: https://github.com/pokt-network/pocket/pull/420#discussion_r1083158417

<img width="918" alt="Screenshot 2023-01-30 at 6 59 45 PM" src="https://user-images.githubusercontent.com/1892194/215651836-634c302e-ecfa-4e8e-9a52-6757b6c72da6.png">

## Goals

- Increase ease of adding and visibility of finding TODOs in our logs
- The TODO messages should be clearly distinguishable from other log messages

## Deliverable

- [ ] TODO Method extending the zerolog api added to the logging module
- [ ] Updated documentation on how to use this
- [ ] Updating all printed TODOs in the code (not the comments) with this the new function

## Non-goals / Non-deliverables

- Updating all the TODOs in the comments with a log message
- Adding new logs

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)

## Testing Methodology

- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @Gustavobelfort 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
Closing this out as unplanned for the foreseeable future. Ticket can be reopened if/when needed.
