### ISSUE TITLE
[CLI] Improve Keybase private-keys sourcing when running in Kubernetes

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#525]
## Objective

Currently, now that we merged #522, the CLI has a `Kubernetes API` dependency because the `private-keys.yaml` file (required by the keybase) is not available locally inside the `Pod` and therefore, in order to have the same init logic, we need to source it by fetching the `Secret` via the `Kubernetes APIs`.

## Origin Document

During the Protocol Hour today (17th Feb 2023) @okdas raised a good point regarding having Kubernetes dependencies inside the CLI at all. The CLI should stay unopinionated and be flexible in terms of sourcing dependencies like the `private-keys.yaml` 

## Goals

- Decouple debug keybase initialization from the core logic
- At a minimum allow to specify a path where to fetch the private-keys from
- Decouple the debug/development private-keys from k8s

## Deliverable

- [ ] Allow specifying a path from where the development/debug private keys should be initialized from
- [ ] Make debug key base initialization a separate process (e.g. different make target) independent of the CLI
		- [ ]  Updated CLI/Keybase code
- [ ] Update the Kubernetes manifests so that the private-keys file is accessible without requiring us to interact with the Kubernetes API at all
	- [ ] Updated Localnet manifests

## Non-goals / Non-deliverables

- Additional modifications to keybase extensions

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @okdas, @Olshansk 

```[tasklist]
### Tasks
- [ ] Add a draft title or issue reference here
```

**Comment by jessicadaugherty** [comment]
@deblasis wdyt about linking with @h5law for this one if he's available?

**Comment by jessicadaugherty** [comment]
Consult with @deblasis on implementation

**Comment by 0xBigBoss** [comment]
>also, another symptom of this is the TODO that is already logged in the codebase:

I fixed the bug in my PR by using go:embed https://github.com/pokt-network/pocket/pull/537/files#diff-4191f8f6d8583a1386ce5793bec85c80d9c99b755dfbd6da9564d817bc0ccdba

Thus, the private keys are available in the binary if my PR gets merged. We could add on top of build/debug.go to further customize the debug localnet envs. 

@jessicadaugherty @deblasis

**Comment by deblasis** [comment]
> > also, another symptom of this is the TODO that is already logged in the codebase:
> 
> I fixed the bug in my PR by using go:embed https://github.com/pokt-network/pocket/pull/537/files#diff-4191f8f6d8583a1386ce5793bec85c80d9c99b755dfbd6da9564d817bc0ccdba
> 
> Thus, the private keys are available in the binary if my PR gets merged. We could add on top of build/debug.go to further customize the debug localnet envs.
> 
> @jessicadaugherty @deblasis

Hey @0xBigBoss!
Sweet... yeah, this is definitely a way to solve the problem. 

If your change gets merged as is I guess the current issue boils down to just sourcing the private-keys from the embed instead of kubernetes. 

Regarding your implementation specifically, I'll comment on your PR (that I haven't seen yet but you tickled my curiosity now!)

**Comment by jessicadaugherty** [comment]
Thanks, guys! Will update the deliverables to reflect the TODO being fixed in #537

**Comment by jessicadaugherty** [comment]
CLI takes too long to initialize. May be resolved by https://github.com/pokt-network/pocket/pull/537

FF yaml behind build flag to only be in build so it doesn't get a private key

**Comment by jessicadaugherty** [comment]
Tysm for the clarifying edit on my last comment @bryanchriswhite #BestCoPM

**Comment by Olshansk** [comment]
@0xBigBoss While we are iterating on #537, thoughts on taking the code you have in `build/debug.go` and splitting it out into a separate PR just to solve the CLI loading issue?

```go
import _ "embed"

// PrivateKeysFile is the pre-generated manifest file for LocalNet debugging
//
//go:embed localnet/manifests/private-keys.yaml
var PrivateKeysFile []byte

func init() {
	if len(PrivateKeysFile) == 0 {
		panic("PrivateKeysFile is empty")
	}
}
```

My personal opinion is that when we build the CLI binary, we should have a `--debug` flag which determines if this yaml file should be embedded via `go:embed` or not. That way it can be preloaded in the development `p1` binary, but easily excluded in prod.

**Comment by 0xBigBoss** [comment]
@Olshansk yeah I'd be happy to add a `--debug` flag or some other mechanism that seems appropriate when building the CLI to include the hard-coded private keys, although I may have more thoughts when I dive in.

CC @deblasis
