### ISSUE TITLE
[Utility][Persistence] Implement change tracking in `UtilityUnitOfWork` to allow ephemeral state and remove side effects

### ISSUE THREAD

**Issue by deblasis** [pokt-network/pocket#564]
## Objective

Extend the `UtilityUnitOfWork` logic so that it transparently works like an ephemeral "WorldState" that becomes valid/persisted only when it's committed successfully. Until then, all changes are tracked, applied **in memory** but **NOT** persisted.

## Origin Document

#562 

## Goals

- Obtain a `PersistenceReadContext` 
- Implement `PersistenceWriteContext` but track changes in memory instead of targeting the datastores
- Implement `Commit` logic that flushes the changes correctly to the real `Persistence` 
- Implement a simple `Rollback` that simply throws away all the ephemeral state

## Deliverable

- [ ] A PR with implementation tending to the goal above
- [ ] Deterministic unit tests to verify the logic above

## Non-goals / Non-deliverables

- 

## General issue deliverables

- [ ] Update the appropriate CHANGELOG(s)
- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`
- [ ] **LocalNet**: verify a `LocalNet` is still functioning correctly by following the instructions at [docs/development/README.md](https://github.com/pokt-network/pocket/tree/main/docs/development)

---

**Creator**: @deblasis 
**Co-Owners**: @Olshansk

**Comment by Olshansk** [comment]
The goals make sense to me. Looking forward to seeing the design & implementation around the tree structures for this!
