### ISSUE TITLE
[Tooling] Add a GitHub bot to validate PR meta

### ISSUE THREAD

**Issue by adshmh** [pokt-network/pocket#864]
## Objective

Streamline contributions by automating (or at-least pointing out the need for) the setting of PR meta, e.g. reviewers, project, labels, etc.

![image](https://github.com/pokt-network/pocket/assets/23505281/37a2521c-fe4d-45fd-9aae-8802400069ce)

## Origin Document

https://github.com/pokt-network/pocket/pull/773/files#r1203112450

## Goals

- Make it easier to open issues/PRs for both new and existing contributors
- Open up the possibility of referring the issue/PR author to docs that may have been overlooked.

## Deliverable
- [ ] A GitHub bot that looks for any missing PR/issue meta and adds a comment addressed to the author.
- [ ] Updated docs, based on https://github.com/pokt-network/pocket/pull/773/files#r1207219131, to which the bot points in its comments
- [ ] (Optional) Some automation of setting PR/issue meta: `Assignee` and `Reviewers` would be good starting points.

## General issue deliverables

- [ ] Update any relevant local/global README(s)
- [ ] Update relevant source code tree explanations
- [ ] Add or update any relevant or supporting [mermaid](https://mermaid-js.github.io/mermaid/) diagrams

## Testing Methodology

- [ ] **Task specific tests or benchmarks**: `make ...`
- [ ] **New tests or benchmarks**: `make ...`
- [ ] **All tests**: `make test_all`

---

**Creator**: [@adshmh ]
**Co-Owners**: [@dylanlott @Olshansk @bryanchriswhite]
